version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build:
            context: ./images/php
            args:
# comment out either PHP82 or PHP74
                PHP_IMAGE: 7.4-fpm                     # PHP74
                PHP_EXT_CONF_FIX: -dir=/usr/include/   # PHP74
#                PHP_IMAGE: "8.2-fpm-bullseye"          # PHP82
#                PHP_EXT_CONF_FIX: ""                   # PHP82
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        build: ./images/mysql
        volumes:
            - ./mysql:/var/lib/mysql
